name: Spring Boot CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build, Test and Sonar Analysis
        run: ./mvnw clean verify sonar:sonar -Dsonar.projectKey=manasa-gulla_pipeline-demo -Dsonar.organization=manasa-gulla -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}